django/conf/project_template/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

twiglet/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    (r'^contact/$', 'webapp.views.contact'),
    (r'^contact_thanks/$', 'webapp.views.contact_thanks'),
    (r'^download/$', 'webapp.views.download'),
    (r'^download_thanks/$', 'webapp.views.download_thanks'),
    (r'^download_thanks_thanks/$', 'webapp.views.download_thanks_thanks'),
    (r'^download_release/$', 'webapp.views.download_release'),
    (r'^how/$', 'webapp.views.how'),
    (r'^features/$', 'webapp.views.features'),
    (r'^showcase/$', 'webapp.views.showcase'),
    (r'^showcase/helloworld/$', 'webapp.views.showcase_helloworld'),
    (r'^showcase/playground/$', 'webapp.views.showcase_showoff'),
    (r'^showcase/generics/$', 'webapp.views.showcase_generics'),
    (r'^showcase/delegates/$', 'webapp.views.showcase_delegates'),
    (r'^showcase/rustici/$', 'webapp.views.showcase_rustici'),
    (r'^showcase/rustici/dirtree_help$', 'webapp.views.showcase_dirtree_help'),
    (r'^showcase/code_license_none/$', 'webapp.views.showcase_license_none'),
    (r'^showcase/code_license_apache_20/$', 'webapp.views.showcase_license_apache_20'),
    (r'^showcase/code_license_mit/$', 'webapp.views.showcase_license_mit'),
    (r'^showcase/code_license_sestoft/$', 'webapp.views.showcase_license_sestoft'),
    (r'^documentation/$', 'webapp.views.cs2jdocumentation'),
    (r'^forums/$', 'webapp.views.forums'),
    (r'^privacy/$', 'webapp.views.privacy_policy'),
    (r'^$', 'webapp.views.home'),
    (r'^util/displaytree/(?P<project>\w+)/(?P<fname>(\w|\.)*)/?$', 'webapp.views.util_display'),
    (r'^util/displaycode/(?P<formatting>(pretty|plain))/(?P<project>\w+)/(?P<fname>(\w|\.)*)/?$', 'webapp.views.util_display_code'),
    (r'^util/download/(?P<project>\w+)/(?P<fname>(\w|\.)*)/?$', 'webapp.views.util_download'),


)

twiglet/webapp/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length=50, blank=True)
    comment = models.TextField()
    contact_date = models.DateTimeField('contact date', auto_now_add=True)
    contact_version = models.CharField(max_length=50, default="unknown")
    def __unicode__(self):
        return "Contact: " + self.name

class Download(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length=50, blank=True)
    comment = models.TextField(blank=True)
    download_version = models.CharField(max_length=50, default="unknown")
    download_date = models.DateTimeField('download date', auto_now_add=True)
    def __unicode__(self):
        return "Download: " + self.name

twiglet/webapp/forms.py
from django.forms import ModelForm, Textarea, TextInput
from webapp.models import Contact
from webapp.models import Download

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        exclude = ('contact_date', 'contact_version')
        widgets = {
            'name': TextInput(attrs={'size': 30, 'minlength' : 3, 'class' : 'entrybox round required'}),
            'email': TextInput(attrs={'size': 30, 'class' : 'entrybox round required email'}),
            'phone': TextInput(attrs={'size': 30, 'class' : 'entrybox round'}),
            'comment': Textarea(attrs={'cols': 65, 'rows': 10, 'class' : 'entrybox round required'}),
        }
        

class DownloadForm(ModelForm):
    class Meta:
        model = Download
        exclude = ('download_date', 'download_version')
        widgets = {
            'name': TextInput(attrs={'size': 30, 'minlength' : 3, 'class' : 'entrybox round required'}),
            'email': TextInput(attrs={'size': 30, 'class' : 'entrybox round required email'}),
            'phone': TextInput(attrs={'size': 30, 'class' : 'entrybox round'}),
            'comment': Textarea(attrs={'cols': 50, 'rows': 10, 'class' : 'entrybox round'}),
        }

twiglet/webapp/views.py
from pygments import formatters, highlight, lexers
from django.conf import settings
from django.shortcuts import get_object_or_404, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.core.mail import EmailMessage
from django.http import Http404
from webapp.forms import ContactForm, DownloadForm
from webapp.utils import get_active_version, get_file_tree, get_file_tree_jstree
from django.core.servers.basehttp import FileWrapper

import os, mimetypes, zipfile
import json
from cStringIO import StringIO

def home(request):
    return render_to_response('twiglet/home.html', {'debugstring':os.getcwd()})

def how(request):
    return render_to_response('twiglet/how.html')

def features(request):
    return render_to_response('twiglet/features.html')

def cs2jdocumentation(request):
    return render_to_response('twiglet/cs2jdocumentation.html')

def showcase(request):
    return render_to_response('twiglet/showcase.html')

def forums(request):
    return render_to_response('twiglet/forums.html')

def privacy_policy(request):
    return render_to_response('twiglet/privacy.html')

##
## Show cases
##

def showcase_helloworld(request):
    csharp_listing = get_file_tree_jstree(os.path.join(settings.TWIGLET_SHOWCASE_DIR, "code", "fizzbuzz", "csharp"), "fizzbuzz", "csnode", "csharp")
    java_listing = get_file_tree_jstree(os.path.join(settings.TWIGLET_SHOWCASE_DIR, "code", "fizzbuzz", "java"), "fizzbuzz", "jnode", "java")
    return render_to_response('twiglet/showcases/fizzbuzz.html', {'csharp_tree_json': json.dumps(csharp_listing), 'java_tree_json': json.dumps(java_listing)})

def showcase_showoff(request):
##    csharp_listing = get_file_tree_jstree(os.path.join(settings.TWIGLET_SHOWCASE_DIR, "code", "fizzbuzz", "csharp"), "fizzbuzz", "csnode", "csharp")
##    java_listing = get_file_tree_jstree(os.path.join(settings.TWIGLET_SHOWCASE_DIR, "code", "fizzbuzz", "java"), "fizzbuzz", "jnode", "java")
    return render_to_response('twiglet/showcases/playground.html')

def showcase_generics(request):
    csharp_listing = get_file_tree_jstree(os.path.join(settings.TWIGLET_SHOWCASE_DIR, "code", "generics", "csharp"), "generics", "csnode", "csharp")
    java_listing = get_file_tree_jstree(os.path.join(settings.TWIGLET_SHOWCASE_DIR, "code", "generics", "java"), "generics", "jnode", "java")
    return render_to_response('twiglet/showcases/generics.html', {'csharp_tree_json': json.dumps(csharp_listing), 'java_tree_json': json.dumps(java_listing)})

def showcase_delegates(request):
    csharp_listing = get_file_tree_jstree(os.path.join(settings.TWIGLET_SHOWCASE_DIR, "code", "delegates", "csharp"), "delegates", "csnode", "csharp")
    java_listing = get_file_tree_jstree(os.path.join(settings.TWIGLET_SHOWCASE_DIR, "code", "delegates", "java"), "delegates", "jnode", "java")
    return render_to_response('twiglet/showcases/delegates.html', {'csharp_tree_json': json.dumps(csharp_listing), 'java_tree_json': json.dumps(java_listing)})

def showcase_rustici(request):
    return render_to_response('twiglet/showcases/rustici.html')

def showcase_dirtree_help(request):
    return render_to_response('twiglet/showcases/dirtree_help.html')

def showcase_license_none(request):
    return render_to_response('twiglet/showcases/license_none.html')

def showcase_license_apache_20(request):
    return render_to_response('twiglet/showcases/license_apache_20.html')

def showcase_license_mit(request):
    return render_to_response('twiglet/showcases/license_mit.html')

def showcase_license_sestoft(request):
    return render_to_response('twiglet/showcases/license_sestoft.html')


##
## Contact Form
##
def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            contact=form.save(commit=False)
            contact.contact_version = get_active_version()
            contact.save()
            cd = form.cleaned_data
            email = EmailMessage("CS2J Online Contact from %s" % cd['name'],
                                 "Name: %(name)s\nEmail: %(email)s\nPhone: %(phone)s\nVersion: %(contact_version)s\nMessage: %(comment)s" % dict(contact_version = get_active_version(), **cd),
                                 'cs2jcontact@twigletsoftware.com',
                                 ['kevin.glynn+contact@twigletsoftware.com'],
                                 headers = {'Reply-To':  cd.get('email')})
            email.send()
            return HttpResponseRedirect(reverse('webapp.views.contact_thanks'))
    else:
        form = ContactForm()
    return render_to_response('twiglet/contact_form.html', {'form': form}, context_instance=RequestContext(request))

def contact_thanks(request):
    return render_to_response('twiglet/contact_thanks.html')

##
##
##

##
## Download Gubbins
##

def download(request):
    return render_to_response('twiglet/download.html')


def download_release(request):
    ## Send a file through Django without loading the whole file into              
    ## memory at once. The FileWrapper will turn the file object into an           
    ## iterator for chunks of 8KB.                                                 
    filename = settings.TWIGLET_RELEASE_DIR + '/cs2j-latest.zip' # Select your file here.                                
    wrapper = FileWrapper(file(filename))
    response = HttpResponse(wrapper, content_type='application/zip')
    response['Content-Disposition'] = 'attachment; filename=cs2j-latest.zip'
    response['Content-Length'] = os.path.getsize(filename)
    response['fred'] = filename
    return response

def download_thanks(request):
    if request.method == 'POST':
        form = DownloadForm(request.POST)
        if form.is_valid():
            download=form.save(commit=False)
            download.download_version = get_active_version()
            download.save()
            cd = form.cleaned_data
            email = EmailMessage("CS2J download by %s" % cd['name'],
                                 "Name: %(name)s\nEmail: %(email)s\nPhone: %(phone)s\nVersion: %(download_version)s\nMessage: %(comment)s" % dict(download_version = get_active_version(), **cd),

                                 'cs2jcontact@twigletsoftware.com',
                                 ['kevin.glynn+download@twigletsoftware.com'],
                                 headers = {'Reply-To':  cd.get('email')})
            email.send()
            request.session['allow_trial_download'] = True
            return HttpResponseRedirect(reverse('webapp.views.download_thanks_thanks'))
    else:
        form = DownloadForm()
    return render_to_response('twiglet/download_thanks.html', {'form': form}, context_instance=RequestContext(request))
        
def download_thanks_thanks(request):
    return render_to_response('twiglet/download_thanks_thanks.html')

##
##
##

##
## Utils (ajax etc.)
##

def util_display(request, project, fname):
    try:
        ## underscores are directory characters
        my_project = os.path.join(*project.split('_'))
        my_dirname = os.path.join(*fname.split('_'))
    
        listing = get_file_tree_jstree(os.path.join(settings.TWIGLET_SHOWCASE_DIR, "code", my_project, my_dirname), project, fname)
        ##listing_ul = tree_to_ul(listing)
        return render_to_response('twiglet/display_tree.html', {'tree_json': json.dumps(listing)})
    except Exception:
        ## todo
        raise


def util_display_code(request, project, fname, formatting='pretty'):
    try:
        ## in project underscores are directory characters
        my_project = os.path.join(*project.split('_'))
        my_fname = os.path.join(*fname.split('_'))

        code_file = os.path.join(settings.TWIGLET_SHOWCASE_DIR, "code", my_project, my_fname)
        if not(os.path.isfile(code_file)):
            raise Http404
        source = open(code_file, 'r')
        if formatting == 'pretty':
            formatted_display = highlight(source.read(),
                                          lexers.get_lexer_for_filename(os.path.basename(my_fname)),
                                          formatters.HtmlFormatter(linenos=True))
        else:
            formatted_display = unicode(source.read(), errors='replace')

        return render_to_response('twiglet/display_code.html', {'project': my_project, 'fname' : my_fname, 'display' : formatted_display, 'formatting' : formatting })
    except Exception:
        ## todo
        raise

def util_download(request, project, fname, mimetype = None):
    try:
        ## in project underscores are directory characters
        my_project = os.path.join(*project.split('_'))
        my_fname = os.path.join(*fname.split('_'))
    
        target = os.path.join(settings.TWIGLET_SHOWCASE_DIR, "code", my_project, my_fname)
        if os.path.isfile(target):
            filename = os.path.basename(target)
            if mimetype is None:
                mimetype, encoding = mimetypes.guess_type(filename)
            wrapper = FileWrapper(file(target))
            response = HttpResponse(wrapper, mimetype=mimetype)
            response['Content-Disposition'] = 'attachment; filename=%s' % filename
            response['Content-Length'] = os.path.getsize(target)
            return response
        elif os.path.isdir(target):
            archive_name = os.path.basename(target)
            if target.endswith(os.sep):
                archive_name = os.path.basename(target[:len(target) - len(os.sep)])
            temp = StringIO()
            archive = zipfile.ZipFile(temp, 'w', zipfile.ZIP_DEFLATED)
            for root, dirs, files in os.walk(target):
                #NOTE: ignore empty directories
                for fn in files:
                    absfn = os.path.join(root, fn)
                    zfn = os.path.join(archive_name, absfn[len(target):]) #XXX: relative path

twiglet/templates/twiglet/base_frame_plain.html
<!DOCTYPE html>
<!-- <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN"> -->
<html>

<head>

{% block loadscriptfiles %}{% endblock%}

<title>{% block title %}Twiglet Software{% endblock %}</title>

{% block loadstylefiles %}{% endblock%}

{% block jquery %} {% endblock %}

{% block analytics %} 
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-25770469-1']);
  _gaq.push(['_setDomainName', 'twigletsoftware.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
{% endblock analytics %}
</head>

<body>

{% block body %}
Insert body here
{% endblock %}

</body>
</html>

twiglet/templates/twiglet/base_generic.html
<!DOCTYPE html>
<!-- <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN"> -->
<html>

<head>

<link rel="shortcut icon" href="http://www.twigletsoftware.com/favicon.ico" />
<script type="text/javascript" src="/static/twiglet/js/jquery-1.6.1.min.js"></script>
<script type="text/javascript" src="/static/twiglet/js/prettify.js"></script>
{% block loadscriptfiles %}{% endblock%}

<title>{% block title %}Twiglet Software{% endblock %}</title>
<link rel="stylesheet" type="text/css" media="all" href="/static/twiglet/css/main.css"/>
<link rel="stylesheet" type="text/css" href="/static/twiglet/css/prettify.css"/>
{% block loadstylefiles %}{% endblock%}

<script>
  $(document).ready(function(){
     // add class current_page_item to menu item for this page
    //alert(window.location.pathname);
    // grey out this page from access menu
    $("#access li.page_item a[href='" + window.location.pathname + "']").parent().addClass("current_page_item"); 
 });

 $(document).ready(function(){
    $(".button").click(function () { 
         if ($(this).attr('target')) {  
             window.location = $(this).attr('target');
         }
      });
});
</script>

{% block jquery %} {% endblock %}

{% block analytics %}
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-25770469-1']);
  _gaq.push(['_setDomainName', 'twigletsoftware.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
{% endblock analytics %}

{% block headmisc %} 
{% endblock headmisc %}
</head>

<body onload="prettyPrint()">
<div id="wrapper">
  <div id="header"> 
   <div id="branding" role="banner"> 
      <div id="site-title"> 
        <span> 
          <a href="/" title="Twiglet Software" rel="home">Twiglet Software</a> 
        </span> 
      </div> 
      <div id="site-description">CS2J: Convert C# to Java
      </div> 
      <img src="/static/twiglet/images/cropped-IMG_1993_2.jpg" width="940" height="150" alt="" /> 
    </div><!-- #branding --> 
                                
    <div id="access" role="navigation"> 
      <div class="skip-link screen-reader-text"><a href="#content" title="Skip to content">Skip to content</a></div> 
      <div class="menu">
        <ul>
          <li class="page_item"><a href="/" title="Home">Home</a></li>
          <li class="page_item"><a href="/download/" title="Get CS2J Now">Get CS2J Now</a></li>
          <li class="page_item"><a href="/how/" title="How CS2J Works">How CS2J Works</a></li>
          <li class="page_item"><a href="/showcase/" title="Showcase">Showcase</a></li>   
          <li class="page_item"><a href="/documentation/" title="Documentation">Documentation</a></li>
<!--          <li class="page_item"><a href="/forums/" title="User Forums">User Forums</a></li> -->
          <li class="page_item"><a href="/contact/" title="Contact">Contact</a></li>
        </ul>
      </div> 
    </div><!-- #access --> 
  </div><!-- #header --> 
                                
<div id="main"> 
  <div id="content" role="main"> 

      {% block body %}
      Insert body here
      {% endblock %}

    <div id="bottombanner">

      {% block bottom %}

      <div class="kgcontainer">

        <div align="center" class="leftcolumntwo">
          <div class="green button" target="{% url webapp.views.download %}">
            <div class="buttonfiller">
              Start Translating
            </div>
          </div>
        </div>

        <div align="center" class="leftcolumntwo">
          <div class="button green" target="{% url webapp.views.contact %}">
            <div class="buttonfiller">
              Got Questions? Ask Us
            </div>
          </div>
        </div>

      </div>
      {% endblock %}
    </div>

  </div>
</div>

<div id="footer" role="contentinfo"> 
  <div id="colophon"> 
    <div id="site-info"> 
	<a href="{% url webapp.views.home %}" title="CS2J: Convert C# to Java" rel="home">CS2J: Convert C# to Java</a> 
    </div><!-- #site-info --> 
   <a href="{% url webapp.views.privacy_policy %}">Privacy Policy</a>
   <div id="site-generator"> 
     <a href="http://www.djangoproject.com/"><img src="https://www.djangoproject.com/m/img/badges/djangosite80x15.gif" border="0" alt="A Django site." title="A Django site." /></a>
   </div><!-- #site-generator --> 
 </div><!-- #colophon --> 
</div><!-- #footer --> 
 
</div>
</body> </html>

twiglet/templates/twiglet/contact_thanks.html
{% extends "twiglet/base_generic.html" %}

{% block title %}Thanks{% endblock title %}

{% block body %}
<br />
Thank you for your interest in CS2J, we will contact you shortly.
<br />
{% endblock body %}

twiglet/templates/twiglet/cs2jdocumentation.html
{% extends "twiglet/base_generic.html" %}

{% block title %}CS2J Documentation{% endblock %}
{% block body %}

<!-- <iframe class="googledoc embedone" src="https://docs.google.com/a/twigletsoftware.com/document/pub?id=1y8JPZJuWUfo3F3_uslynmJf05FfBT8bii-FfhkZtC_I&amp;embedded=true"></iframe> -->

<iframe class="googledoc embedone" src="https://docs.google.com/document/pub?id=1y8JPZJuWUfo3F3_uslynmJf05FfBT8bii-FfhkZtC_I&amp;embedded=true"></iframe>

{% endblock body %}

twiglet/templates/twiglet/display_code.html
{% extends "twiglet/base_frame_plain.html" %}

{% block loadstylefiles %}
{% if formatting == 'pretty' %}
<link rel="stylesheet" type="text/css" media="all" href="/static/twiglet/css/main.css"/>
<link rel="stylesheet" type="text/css" media="all" href="/static/twiglet/css/pygments.css"/>
{% endif %}
{% endblock %}

{% block title %}Display {{ fname }}{% endblock title %}

{% block body %}

{% if formatting == 'pretty' %}

{{ display|safe }}

{% else %}
<pre>

{{ display }}

</pre>
{% endif %}

{% endblock body %}

twiglet/templates/twiglet/display_tree.html
{% extends "twiglet/base_generic.html" %}

{% block loadscriptfiles %}
<script type="text/javascript" src="/static/twiglet/js/jquery.cookie.js"></script>
<script type="text/javascript" src="/static/twiglet/js/jstree_pre1.0_stable/jquery.jstree.js"></script>
{% endblock %}
{% block loadstylefiles %}
<link rel="stylesheet" type="text/css" media="all" href="/static/twiglet/css/pygments.css"/>
{% endblock %}

{% block jquery %}
<script>

function customMenu(node) {
    // folder
    if ($(node).hasClass("folder")) {
      return {
        downloadItem: { 
            label: "Download (as zip)",
            icon: "/static/twiglet/images/disk.png",
            action: function (click_node)
              {
                 project = $("a",click_node).attr("project");
                 fname = $("a",click_node).attr("fname");
                 base = "{% url webapp.views.util_download 'PROJECT' 'FNAME' %}";
                 url = base.replace('PROJECT', project).replace('FNAME', fname);
                 window.location=url;
             }
        }
     };
    }
  else { // leaf
     return {
        downloadItem: { 
            label: "Download",
            icon: "/static/twiglet/images/disk.png",
            action: function (click_node)
              {
                 project = $("a",click_node).attr("project");
                 fname = $("a",click_node).attr("fname");
                 base = "{% url webapp.views.util_download 'PROJECT' 'FNAME' %}";
                 url = base.replace('PROJECT', project).replace('FNAME', fname);
                 window.location=url;
             }
        },
        rawViewItem: { 
            label: "View without formatting",
            icon: "/static/twiglet/images/text_align_left.png",
            action: function (click_node)
              {
                 project = $("a",click_node).attr("project");
                 fname = $("a",click_node).attr("fname");
                 base = "{% url webapp.views.util_display_code 'plain' 'PROJECT' 'FNAME' %}";
                 url = base.replace('PROJECT', project).replace('FNAME', fname);
                 window.open(url);
             }
        }
     };
    }
}

  $(document).ready(function(){
     $("#dirtree1").jstree(
         { json_data : { data : {{ tree_json|safe }} },
	   plugins : [ "themes", "json_data", "cookies", "contextmenu"],
           core : { animation : 200 },
           cookies : { prefix : "tree1", opts : { path : "/" } },
           contextmenu : { items : customMenu, show_at_node : false }
       });
     $("#dirtree1").delegate("a","click", function (e) { 
         if ($(this).hasClass('folder')) {  // is the node clicked a folder?
             $("#dirtree1").jstree("toggle_node", this); 
             e.preventDefault(); 
             return false;
         }
      });
});
</script>

{% endblock %}

{% block title %}Display Tree{% endblock title %}

{% block body %}

<div id="dirtree1">
</div>

{% endblock body %}

twiglet/templates/twiglet/download.html
{% extends "twiglet/base_generic.html" %}

{% block title %}Download CS2J{% endblock title %}

{% block body %}

<div class="standoutblock kgcontainer">
<div class="leftcolumntwo">
   <h2 class="bold" align="center">Download the latest CS2J Release</h2>

CS2J is a windows executable.  It runs on other platforms if you first install <a href="http://www.go-mono.com/mono-downloads/download.html">Mono</a>.
Download the latest version of CS2J and try it on your own code.  
  <div align="center">
  <div class="button" target="{% url webapp.views.download_thanks %}">
  <div class="buttonfiller">
    Download CS2J
  </div>
  </div>
  </div>
</p>
</div>

<div class="rightcolumntwo">
   <h2 class="bold" align="center">Go to the Source (code)</h2>

The code to CS2J and CS2JLibrary are available from github. Come and help us make CS2J better. You can browse or clone the current contents of the git repository using the <a href="https://github.com/twiglet/cs2j">web interface</a>.
<p>
To build the code on windows you should install .Net framework 4.  To build the code on other platforms you should install <a href="http://www.go-mono.com/mono-downloads/download.html">Mono</a> and <a href="http://ant.apache.org">Ant</a>.
<p>  
</div>
</div>

{% endblock body %}

{% block bottom %}
{% endblock bottom %}

twiglet/templates/twiglet/download_thanks.html
{% extends "twiglet/base_generic.html" %}

{% block loadscriptfiles %}
<script type="text/javascript" src="/static/twiglet/js/jquery.validate-1.8.1.min.js"></script>
{% endblock%}

{% block jquery %}
<script>
  $(document).ready(function(){
    $("label:not(.error)").append(":");
    $("#downloadForm").validate();
  });
</script>
{% endblock %}

{% block title %}Thanks{% endblock title %}


{% block body %}
<div align="center">
Thank you for your downloading CS2J.  Your download should start
automatically, if not <a href="{% url webapp.views.download_release %}">Click Here</a>.
</div>
<div class="kgcontainer standoutblock padtext">

We love hearing about the uses people have found for CS2J and would
appreciate it if you could fill in the form below with some brief
information about what you plan to do with CS2J. 
<p>
If you want to contact the people behind CS2J then you can use the information on the
<a href="{% url webapp.views.contact %}">Contact</a> Page or try the <a href="{% url webapp.views.forums %}">User Forums</a>.

<p>

<form class="cmxform" id="downloadForm" method="post" action="">
  {% csrf_token %}
  <fieldset>
    <label for="cname">Name<sup>*</sup></label>
     {{ form.name }}
     {% for error in form.name.errors %}
        <label for="id_name" generated="true" class="error">{{ error|escape }}</label>
     {% endfor %}
   </p>
   <p>
     <label for="cemail">Email<sup>*</sup></label>
     {{ form.email }}
     {% for error in form.email.errors %}
        <label for="id_email" generated="true" class="error">{{ error|escape }}</label>
     {% endfor %}
   </p>
   <p>
    <label for="ccomment">Message</label><br/>
     {{ form.comment }}
     {% for error in form.comment.errors %}
        <label for="id_comment" generated="true" class="error">{{ error|escape }}</label>
     {% endfor %}
   </p>
   <p>
     <input class="submit button" style="color:white" type="submit" value="Submit"/>
   </p>
 </fieldset>
</form>
</div>
<br/>

<iframe src="{% url webapp.views.download_release %}" style="display:none;" />

{% endblock body %}